language: node_js
node_js: false
env:
  global:
    - SAUCE_ACCESS_KEY=3259dd1e-a9f2-41cc-afd7-855d80588aeb
    - SAUCE_USERNAME=elasticsearch-js
matrix:
  include:
    - node_js: "0.8"
      env: ES_BRANCH=master
    - node_js: "0.10"
      env: ES_BRANCH=master COVERAGE=1
    - node_js: "0.10"
      env: ES_BRANCH=0.90 NODE_UNIT=0
    - node_js: "0.10"
      env: ES_RELEASE=0.90.9 ES_BRANCH=0.90 NODE_UNIT=0
    - node_js: "0.10"
      env: ES_RELEASE=0.90.8 ES_BRANCH=0.90 NODE_UNIT=0
    # - node_js: "0.10"
    #   env: NODE_UNIT=0 NODE_INTEGRATION=0 TEST_BROWSER='chrome'
    # - node_js: "0.10"
    #   env: NODE_UNIT=0 NODE_INTEGRATION=0 TEST_BROWSER='firefox'
    # - node_js: "0.10"
    #   env: NODE_UNIT=0 NODE_INTEGRATION=0 TEST_BROWSER='ie'
  exclude:
    - node_js: false

script: ./scripts/ci.sh
email:
  recipients:
    - spencer.alger@elasticsearch.com
  on_success: change
  on_failure: always