version: '3.2'
services:
  client:
    image: docker.elastic.co/clients/elasticsearch-js:${NODE_JS_VERSION:-10}
    build:
      context: ..
      dockerfile: .ci/Dockerfile
      args:
          NODE_JS_VERSION: ${NODE_JS_VERSION:-10}
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ..:/usr/src/app
      # This will mount the node_modules directory
      # to the host machine using the buildtime directory.
      - /usr/src/app/node_modules
      - esvol:/tmp
    networks:
      - esnet
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-7.0.0-beta1}
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://snapshot.*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
networks:
  esnet:
volumes:
  esvol:
